# https://hub.docker.com/r/keymetrics/pm2/
image: keymetrics/pm2:latest-alpine

# Available stage
stages:
  - deploy

# Job
deploy_dev:
  stage: deploy
  script:
    # Update server
    - echo "====== Deploy to server ======"
    - apk --update upgrade
    - apk add git openssh bash
    # Add target server`s secret key
    - mkdir ~/.ssh
    - echo $TARGET_SERVER_SECRET_KEY_BASE64 | base64 -d > ~/.ssh/id_rsa
    - chmod 700 ~/.ssh && chmod 600 ~/.ssh/*
    - echo "====== SSH connection ======"
    - ssh -o StrictHostKeyChecking=no -T $TARGET_SERVER_USER@$TARGET_SERVER_HOST -p $TARGET_SERVER_PORT
    # Setup Deploy if not exist else update deploy
    - echo "====== Setup or Update target server directories ======"
    - ( if [ ! -d ("/home/" + $TARGET_SERVER_USER + "/" + $APP_NAME + "/dev") ]; then pm2 deploy ecosystem.config.js development setup 2>&1 || true; else pm2 deploy ecosystem.config.js development update 2>&1; fi )
    - echo "====== Make deploy ======"
    - pm2 deploy ecosystem.config.js development
  environment:
    name: staging
    url: $REDIRECT_DOMAIN
  only:
  - dev
