# image: keymetrics/pm2:latest-slim
image: keymetrics/pm2:latest-alpine

stages:
  - deploy

deploy_prod:
  stage: deploy
  script:
    - echo "====== Deploy to production server ======"
    - apk --update upgrade
    - echo "options ndots:5" >> /etc/resolv.conf
    - apk add git openssh bash
    # - echo "Acquire::http::Proxy \"$HTTP_PROXY\";" >> /etc/apt/apt.conf
    # - apt-get update
    # - apt-get upgrade
    # - apt-get install git openssh bash
    # Add target server`s secret key
    - mkdir ~/.ssh
    - echo $TARGET_SERVER_SECRET_KEY_BASE64 | base64 -d > ~/.ssh/id_rsa
    - chmod 700 ~/.ssh && chmod 600 ~/.ssh/*
    - echo "Test ssh connection"
    - ssh -o StrictHostKeyChecking=no -T $TARGET_SERVER_USER@$TARGET_SERVER_HOST -p $TARGET_SERVER_PORT
    # Deploy
    - echo "Setup target server directories"
    - pm2 deploy ecosystem.config.js production setup 2>&1 || true
    - echo "make deploy"
    - pm2 deploy ecosystem.config.js production
  environment:
    name: deploying
  only:
  - master
  - dev