image: keymetrics/pm2:latest-alpine

stages:
  - deploy

# Job de déploiement de l'environnement de développement
deploy_dev:
  stage: deploy
  script:
    - echo "====== Deploy to server ======"
    - apk --update upgrade
    - apk add git openssh bash
    # Add target server`s secret key
    - mkdir ~/.ssh
    - echo $TARGET_SERVER_SECRET_KEY_BASE64 | base64 -d > ~/.ssh/id_rsa
    - chmod 700 ~/.ssh && chmod 600 ~/.ssh/*
    - echo "Test ssh connection"
    - ssh -o StrictHostKeyChecking=no -T $TARGET_SERVER_USER@$TARGET_SERVER_HOST -p $TARGET_SERVER_PORT
    # Deploy
    - echo "Setup target server directories"
    - pm2 deploy ecosystem.config.js development setup 2>&1 || true
    - echo "make deploy"
    - pm2 deploy ecosystem.config.js development
  environment:
    name: staging
    url: $REDIRECT_DOMAIN
  only:
  - dev
