# https://hub.docker.com/r/keymetrics/pm2/
image: keymetrics/pm2:latest-alpine

# Available stage
stages:
  - deploy

# Job
deploy_dev:
  stage: deploy
  script:
    # Update server
    - echo "====== Deploy to server ======"
    - apk --update upgrade
    - apk add git openssh bash
    # Add target server`s secret key
    - mkdir ~/.ssh
    - echo $TARGET_SERVER_SECRET_KEY_BASE64 | base64 -d > ~/.ssh/id_rsa
    - chmod 700 ~/.ssh && chmod 600 ~/.ssh/*
    - echo "====== SSH connection ======"
    - ssh -o StrictHostKeyChecking=no -T $TARGET_SERVER_USER@$TARGET_SERVER_HOST -p $TARGET_SERVER_PORT
    # Set ENV
    - echo "====== Set ENV ======"
    - echo "MONGO_URI_FULL  = $MONGO_URI_FULL"  > .env
    - echo "EXPRESS_SECRET  = $EXPRESS_SECRET"  >> .env
    - echo "EXPRESS_HTTPS   = false"            >> .env
    - echo "REDIRECT_DOMAIN = $REDIRECT_DOMAIN" >> .env
    - echo "SMTP_HOST       = $SMTP_HOST"       >> .env
    - echo "STMP_PORT       = $STMP_PORT"       >> .env
    - echo "SMTP_SECURE     = $SMTP_SECURE"     >> .env
    - echo "SMTP_USERNAME   = $SMTP_USERNAME"   >> .env
    - echo "SMTP_PWD        = $SMTP_PWD"        >> .env
    - echo "SMTP_FROM       = $SMTP_FROM"       >> .env
    - echo "WEBSITE_NAME    = $WEBSITE_NAME"    >> .env
    # Deploy
    - echo "====== Setup target server directories ======"
    - pm2 deploy ecosystem.config.js development setup 2>&1 || true
    - echo "====== make deploy ======"
    - pm2 deploy ecosystem.config.js development
  environment:
    name: staging
    url: $REDIRECT_DOMAIN
  only:
  - dev
